spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      schema: contacts_schema

